### ISSUE TITLE
CM Issue: Unable to save in default folder

### ISSUE THREAD

**Issue by RyanMaggie** [JCWiley/Character-Manager#6]
CM always opens up the Document folder as the default saving location (and this location never changes), however I can't save in the Document folder, saying that the file cannot be found (even though I am trying to create it). Just using text or numbers does not sway this error.

![image](https://user-images.githubusercontent.com/69267327/89456539-e3d81e80-d718-11ea-8dde-cefe6d529bcf.png)

**Comment by JCWiley** [comment]
Issue mitigated through changes to filepath management. Initial error not resolved.

**Comment by JCWiley** [comment]
Applies to earlier version.
